### ISSUE TITLE
Smart Charging

### ISSUE THREAD

**Issue by Maggi0r** [Zendure/Zendure-HA#461]
I have a problem my smart Charging isn't working. I've tried everything bypass on and off. It doesn't change anything. Smart charging doesn't start. If I understand correctly, with smart charging, it first feeds in the power needed in the house, and the rest goes into the battery. Here's someone you can help me with. Regards, Maggi.

**Comment by FireSon** [comment]
@Maggi0r It might be related to many things:

1) did you set the device cluster(s) if they are on 'unused', smart mode will not work!
2) Do you have a p1 meter with the correct value, >0 if your house is consuming ernergy <0 if it is producing
3) Are the device(s) connected a do the report any values

So it is impossible to help, if you do not specify a bit better what is not working. Also debug logging is helpful. Maybe you can search the GitHub repository, since many questions have been asked and ansered before 😄

**Comment by Maggi0r** [comment]
Hello Fireson, the P1 sensor is providing values. When drawing from the grid, it's above zero; when feeding in, it's below zero or negative. The normal "Smart Power Control" works. What unfortunately doesn't work is the "Smart Charge Only" function. If I understand correctly, that's how it's designed: When there's a power demand in the house, this amount is fed in, and the rest goes into the battery.

Unfortunately, this doesn't work. I don't use a cluster and don't have this option available in the integration. My current version is 1.1.0pre3.


Best regards, Maggi

**Comment by FireSon** [comment]
@Maggi0r Can you check this with the latest version 1.1.0-pre13? The were some issues with the legacy devices which I have fixed

**Comment by Maggi0r** [comment]
Ok, I´ll test it this weekend and get back to you. 

Regards Maggi

**Comment by Kieft-C** [comment]
[Version 1.1.2-pre2](https://github.com/Zendure/Zendure-HA/releases/tag/1.1.2-pre2)
Seems to work. test this release.

**Comment by harrymayr** [comment]
I'm not sure, if this special case (Smart Charging only) is handled better than before.
In general there is a little lack of handling the PV-input connected to the devices. Not sure, if this changed, but in the past, FireSon (and also I) have only AC charging capabilities, so a test is difficult for us.

**Comment by Maggi0r** [comment]
I've now updated to version 1.1.3, but the "Smart Only Charge" feature still doesn't work.
Or am I simply misunderstanding this function? My understanding is that when this function is enabled, only the PV power not needed in the house goes into the battery. So, basically, surplus charging of the battery?

Correct me if I'm misunderstanding this. That's what I'd like to achieve.

If you need anything, I'd be happy to help. If I can.

Best, Maggi

**Comment by harrymayr** [comment]
Also in 1.1.3 is the power distribution not yet changed. We are working on it.

**Comment by Martinvdm** [comment]
I have the same issue. Seems that changing from Smart Matching to Smart Charging does not change at all. It keeps on discharching, but I was expected to go Inactive where there is >0 load from p1 and goes Charging when there is solar production from p1.

**Comment by harrymayr** [comment]
The above PR #702 does not yet fullfil the expectation. Need to do some more changes.

**Comment by harrymayr** [comment]
OK, with the actual repository and the PR #702 (added some changes today), smart charging should work as expected. I assume that there will be a 1.1.4-pre3 version the next days.

**Comment by FireSon** [comment]
@Maggi0r Can you check version 1.1.4-pre3? Please open a new issue if in that version the problem persists!
