### ISSUE TITLE
Disabled entries that have been removed in (1.1.0) update can't be removed

### ISSUE THREAD

**Issue by noseshimself** [Zendure/Zendure-HA#616]
I have disabled several sensors because they were not relevant to my system:

<img width="499" height="364" alt="Image" src="https://github.com/user-attachments/assets/9827f19e-9c27-448b-b780-48636e88ca10" />

In order to get fully rid of them I tried enabling them as disabled entries can't be deleted. 

Turns out: You can't delete them when enabled either because they do not receive a value and thus

<img width="644" height="806" alt="Image" src="https://github.com/user-attachments/assets/0b3a8f67-896b-46e1-8903-e82a207961d7" />

with the "Delete" button being disabled.

I don't know if this has to be addressed by the core providing that function or if it is a problem with this integration but even if it is a core problem it would be nice if you forwarded this to the correct project.

**Comment by harrymayr** [comment]
Even on a restart of HA, these sensors are still visible or not able to delete?

**Comment by noseshimself** [comment]
Yes. Even after multiple restarts. I have another object I can't remove either. For some unrelated reason I accidentally reset one of the Hyper 2000 and had it show up with its default name. Now I have a "Hyper 2000" I can disable but not delete:

<img width="1117" height="252" alt="Image" src="https://github.com/user-attachments/assets/bc58c861-bc47-45c3-a524-fc84d3fd0eb5" />

<img width="1238" height="252" alt="Image" src="https://github.com/user-attachments/assets/c95f682e-1df7-437e-9452-8751b44faf19" />

<img width="391" height="252" alt="Image" src="https://github.com/user-attachments/assets/dd021e0e-c8fd-4094-853f-4d4311c5272f" />

<img width="509" height="380" alt="Image" src="https://github.com/user-attachments/assets/a474724b-24f4-44d7-9ad1-13436328e4e8" />

**Comment by FireSon** [comment]
@noseshimself Were you able to fix this?

**Comment by noseshimself** [comment]
No. It's still there. I could of course "fix" it by starting over but I would lose something you could use for testing (I could re-create it by deleting a device from my account and re-adding it under a different name but setting up the HEMS is a major pain).

**Comment by Linus86529** [comment]
I have a similar problem with the SF800, which was deliberately disabled because the home-assistant.log was full. After restarting the HA system, a second SF800 was detected. The screenshot shows the ghost SF800 with fewer entities than the original SF800.

By the way, a strange observation from today. The problem with the ghost batteries was fixed a few weeks ago. I have no idea why or how this could happen again. The screenshot shows two ghost batteries that have fewer entities than the original batteries.

I think it's time for a clean install again.

<img width="936" height="1081" alt="Image" src="https://github.com/user-attachments/assets/6f53d87b-f590-4044-a736-8b7a8c35733b" />

**Comment by Linus86529** [comment]
I forgot to mention that the value of 'Verfügbare Energie' was calculated correctly after deactivation of the two Ghost Batteries and after pressing 'RESET Verbindung' for the Hub1200 and theHyper2000.

**Comment by Linus86529** [comment]
The value 'Verfügbare Energie' shown in [this issue](https://github.com/Zendure/Zendure-HA/issues/680#issue-3331904558) looks identical to the value I had an hour ago.

**Comment by noseshimself** [comment]
<img width="1456" height="550" alt="Image" src="https://github.com/user-attachments/assets/3fb51cd8-2747-415c-a707-33c3a61d9619" />

<img width="1345" height="272" alt="Image" src="https://github.com/user-attachments/assets/2d3452c9-b476-43ae-a0a7-ee5c1dea22ca" />

The problem is still there and I still believe that it is a general Home-Assassin-UI problem.  If it is enabled, all I can do is disable it. If it is disabled, all I can do is enable it. There just is no UI element to delete it at all...
