### ISSUE TITLE
[Bug] Zendure doesn't keep Apartment at 0W after reaching 100% SoC

### ISSUE THREAD

**Issue by Tronnic** [Zendure/Zendure-HA#686]
### Home Assistant Version

2025.7.2 Core / 2025.08.1 Supvervisor

### Zendure Integration Version

v1.1.3

### Describe the bug

Hello everyone, I installed my Zendure SolarFlow800 Pro yesterday evening. So today is it's first day of running.
I use a Shelly 3EM Pro to measure my home power usage. The Zendure Addon is configured to use it. 

<img width="657" height="771" alt="Image" src="https://github.com/user-attachments/assets/59083e84-a8f7-4b4e-8729-96d4b19c668f" />

If you look at the graph at the bottom, while the battery was charging, my home power usage was kept pertty much exactly at 0W which I was VERY happy about. 

However, after reaching 100% SoC, it's really having trouble keeping the grid power usage at 0W. It says it's only pruducing 70W Solar, which is clearly wrong. The sun is shining bright and the modules should deliver around 1200W at this time. 

Is there something I did wrong? I'm somewhat dissapointed that I use 100-200W even if the sun is shining bright. 

SolarFlow 800 Pro:
<img width="422" height="791" alt="Image" src="https://github.com/user-attachments/assets/baf1b6b6-0852-430d-b68c-d14a328e7d49" /> <img width="402" height="1066" alt="Image" src="https://github.com/user-attachments/assets/e169ace1-5d60-4eb1-aec6-f86c991b8b8c" />
<img width="418" height="1122" alt="Image" src="https://github.com/user-attachments/assets/ea0ff67b-bbe8-4e08-af3a-746b7b9a41ed" /> <img width="388" height="952" alt="Image" src="https://github.com/user-attachments/assets/5ce09b2a-e630-4562-8399-9a2df596a3f8" />

Battery:
<img width="388" height="655" alt="Image" src="https://github.com/user-attachments/assets/3abb557f-41b5-4d21-b1fb-48996c165bbf" />

Zendure Manager:
<img width="397" height="563" alt="Image" src="https://github.com/user-attachments/assets/82634150-0127-4b6b-9e6c-8d6a9451176e" />

Thanks for any help I can get. The Firmware of the Zendure is Up-to-date. 

### To Reproduce

1. Install HACS Zendure-HA
2. Setup SolarFlow800 Pro
3. Set everythting up
4. Let device run normally

So basically nothing special

### Expected Behaviour

After the Battery SoC Reaches 100%, the power of solar should still keep the house at 0W, or even pass trough full solar power. Whatever works. 

### What device are you using?

SF800 Pro

### Log Extracts

```shell
All I could find when searching for "Zendure" in the HA Logs:

Logger: custom_components.zendure_ha.device
Source: custom_components/zendure_ha/device.py:490
integration: Zendure Home Assistant Integration (documentation, issues)
First occurred: 1:13:33 PM (14 occurrences)
Last logged: 1:17:35 PM

HttpPost error SolarFlow 800 Pro Cannot connect to host 192.168.1.147:80 ssl:default [Connect call failed ('192.168.1.147', 80)]!

----

Logger: custom_components.zendure_ha.device
Source: custom_components/zendure_ha/device.py:479
integration: Zendure Home Assistant Integration (documentation, issues)
First occurred: 1:13:22 PM (48 occurrences)
Last logged: 1:17:35 PM

HttpGet error SolarFlow 800 Pro Cannot connect to host 192.168.1.147:80 ssl:default [Connect call failed ('192.168.1.147', 80)]!

----

Logger: py.warnings
Source: custom_components/zendure_ha/entity.py:13
integration: Zendure Home Assistant Integration (documentation, issues)
First occurred: August 19, 2025 at 7:33:01 PM (1 occurrence)
Last logged: August 19, 2025 at 7:33:01 PM

/usr/local/lib/python3.13/site-packages/stringcase.py:247: SyntaxWarning: invalid escape sequence '\W' return re.sub("\W+", "", string)
```

**Comment by Tronnic** [comment]
Okay, so after looking at my own screenshots, I noticed that "Ausgangslimit" and "Eingangslimit" is set to very low. I set this to the maximum yesterday. Also I monitored the whole day today, theses limits were not that low while charging. See the graph here (my idle grid usage of my home is at about 250-300W)

<img width="2220" height="718" alt="Image" src="https://github.com/user-attachments/assets/20783f8e-9ca2-4391-8841-7cc4c1f8e0b4" />

It seems to be working now after setting these sliders to max agian

<img width="645" height="760" alt="Image" src="https://github.com/user-attachments/assets/8adba34a-649c-4147-8436-3fcc23647675" />

I will report back if anything changes.

**Comment by Tronnic** [comment]
Allright, so after a few minutes the slider went back to 33W. Why? How can I keep it at max? When set to max, everything works. I mean sure I could create an automation for that, but I guess thats not pracitcal or good for flash.

<img width="417" height="795" alt="Image" src="https://github.com/user-attachments/assets/f3c8ec10-a98a-4b94-9f9b-9faab63c2de4" />

Just while typing this, the slider once again changed. I guess it represents what the battery should be set at to reach 0, which is clearly not enough. 

Is there a way to fix this?

**Comment by itapower** [comment]
https://github.com/user-attachments/assets/06106c32-34e9-487b-a701-814d5791d7ef

Hi,

I have the same issue on a Hyper 2000. I have 1.1.4 pre installed. Before this integration number I had issues with the smart matching mode, which are now solved. Everything is working fine, until the battery is full loaded. The solar power input is dropping without any reason (and it's not because of some clouds). I have attached a video (60 sec.), in which you can observe the drop and than restart to the full solar power input. Please look at the right diagram (Watt)

**Comment by Zanooon97** [comment]
Same issue since days 

i looked around

device.py

    async def power_get(self) -> int:
        """Get the current power."""
        if not self.online or self.packInputPower.state is None or self.outputPackPower.state is None:
            return 0
        self.powerAct = self.packInputPower.asInt - self.outputPackPower.asInt
        if self.powerAct != 0:
            self.powerAct += self.solarInputPower.asInt
        return self.powerAct

i  have no sun the next days to test, but this logic say when 0 watt out and in from battery, then ignor solarpower, so Actual power 0,


try this:

    async def power_get(self) -> int:
        """Get the current power."""
        if not self.online or self.outputHomePower.state is None or self.gridInputPower.state is None:
            return 0
        self.powerAct = self.outputHomePower.asInt - self.gridInputPower.asInt
        return self.powerAct

if you watch clearly you see a changing of watts 700WPV / 300WGrid -> 700WGrid 300WPV -> 700WPV / 300WGrid

**Comment by harrymayr** [comment]
gridInputPower is always 0 for non AC load capable devices 

I think the solarpower need to be added depending on the Bypass

**Comment by Zanooon97** [comment]
okei I dont knew that, that non ac load capable devices exist here by zendure.
So we need to change it:

and add this entity in the top:

        self.outputHomePower = ZendureSensor(self, "outputHomePower", None, "W", "power", "measurement")


around Line 348:

    async def power_get(self) -> int:
        """Get the current power."""
        if not self.online or self.packInputPower.state is None or self.outputPackPower.state is None:
            return 0
        self.powerAct = self.packInputPower.asInt - self.outputPackPower.asInt
        if self.powerAct != 0:
            self.powerAct += self.solarInputPower.asInt
        elif self.powerAct == 0 and self.outputHomePower.asInt is not None:
            self.powerAct = self.outputHomePower.asInt
        return self.powerAct

around Line 441:

    async def power_get(self) -> int:
        """Get the current power."""
        json = await self.httpGet("properties/report")
        self.mqttProperties(json)

        # return zero if device is offline or states are unknown
        if not self.online or self.packInputPower.state is None or self.outputPackPower.state is None:
            return 0

        self.powerAct = self.packInputPower.asInt - self.outputPackPower.asInt
        if self.powerAct != 0:
            self.powerAct += self.solarInputPower.asInt
        elif self.powerAct == 0 and self.outputHomePower.asInt is not None:
            self.powerAct = self.outputHomePower.asInt
        return self.powerAct

So we are not touching the code we are only adding a "backup" for the Actual Power

In my opinion it is better to calculate with outputHomePower instead of solarPower, the solarpower can be 280W and the effective output power is 250W 

@spireyn-dp can you test this?

**Comment by spireyn-dp** [comment]
The bug was already reported in https://github.com/Zendure/Zendure-HA/issues/646
But I have the exact same problem with a SF 2400 AC.
After reaching soc of 100%, it's like the battery is not used anymore.
Battery is slowly losing power 99% ,98% even if solar power still present and when solar power is not enough the battery is not outputting power to compensate . 

The only way to restart the smart matching is to change to Manual or Off mode, change values manually, then switch back to Smart Mode

**Comment by Zanooon97** [comment]
My Bypass entity is only changing to ON when i have gridreverse ON
I cant work with taht😬
@harrymayr

**Comment by Zanooon97** [comment]
> gridInputPower is always 0 for non AC load capable devices
> 
> I think the solarpower need to be added depending on the Bypass

So this should also work 😆
self.powerAct = self.packInputPower.asInt - self.outputPackPower.asInt + self.solarInputPower.asInt

**Comment by Zanooon97** [comment]
@FireSon Hello, whats the reason about this exclusion of solarpower when battery is inactive?

**Comment by Tronnic** [comment]
My solution for now is to set bypass to always on.

<img width="478" height="66" alt="Image" src="https://github.com/user-attachments/assets/8c0401e2-493d-4622-8b2f-4a68ef6fd037" />

When battery is full, all the power will go into the grid. It produces more heat, but at least I don't loose energy. I would love to have a setting at some point to set passtrough whenn full to a limit of 100W or something. This way, small fluctuations don't cost anything.

**Comment by Zanooon97** [comment]
@Tronnic https://github.com/Zendure/Zendure-HA/issues/646

**Comment by spireyn-dp** [comment]
@Zanooon97 tried it this week-end without success. I tried with a cap at 100%, still stuck. And next day I put the maximum SoC at 95% but then was stuck at 95% slowly losing power to 94%, 93%, ... instead of compensating the grid consumption.

I forgot to mention that in my case the solar panels are not directly connected to the Solarflow 2400, I have a separate inverter injecting power in my electric installation, and the SF is consuming/injecting via the socket cable.

So in my case the bypass mode will not change anything I guess.

I will try the PR from @harrymayr https://github.com/Zendure/Zendure-HA/pull/702

**Comment by Zanooon97** [comment]
I have made it for my SF800 device. look at the pullrequest from harry, and update to the latest pre 2 version.
https://github.com/Zendure/Zendure-HA/pull/702

**Comment by harrymayr** [comment]
> I have made it for my SF800 device. look at the pullrequest from harry, and update to the latest pre 2 version. [#702](https://github.com/Zendure/Zendure-HA/pull/702)

First update to pre2, than add the changes in the PR 😉
Or better, use the actual code from the repository, than add the changes.

![Image](https://github.com/user-attachments/assets/d97398e2-35d2-472b-bbeb-1e18ce5f1bec)

**Comment by spirann** [comment]
So I made different tests cases, but weather was cloudy so it took some times.
-  1.1.4 pre2 only: no fix but introduce a new bug similar to #726 , in the morning switching from "off" to "smart matching" doesn't trigger discharge of the battery anymore + various case during the day when solar is insufficient and "smart matching" doesn't switch from charge to discharge. So still stuck a 100% but at lower soc too
- 1.1.4 pre2 + PR from @harrymayr : same results
- download full zip from @harrymayr and replace all integration : same results.

The only thing I didn't try is 1.1.3 + PR but not sure it is possible.

Small recap of my  config:

SF2400AC, Solar via electrical installation not directly into the SF, Power manager "off" and manual configuration during night (low price hours) and "smart matching" during day (high price hours).

**Comment by Zanooon97** [comment]
@spirann make a debugg log when you got this problems

**Comment by Tronnic** [comment]
was this fixed? I'm still running PR702

**Comment by spirann** [comment]
I'm running 1.1.4-pre7 and don't have the bug anymore.
